

#define CHASH_ELEMENT_NOT_EXIST 400
#define CHASH_WRONG_TYPE 401
#define  CHASH_NOT_HAVE_KEY 402
#define  CHASH_NOT_ITERABLE 403
#define CHASH_NOT_VALID_INDEX 404
#define  CHASH_ELEMENT_IS_NULL 405
#define  CHASH_LOWER_NUMBER 406